model:
  name: "deepseekvl2tiny"
  model_name: "deepseek-vl2-tiny"
  model_path: "deepseek-ai/deepseek-vl2-tiny"
  max_new_tokens: 512
  temperature: 0
  top_p: 1.0
  device: "cuda"
  device_map: "auto"
  dtype: "bfloat16"
  seed: 42
  batch_size: 1

dataset:
  root: ""  # Set your dataset root
  path: "index/human_detection/day.jsonl"

output:
  save_path: "./results/deepseekvl2tiny_results.jsonl"