model:
  "name": "qwen" # model identifier
  "model_name": "qwen"
  "model_path": "Qwen/Qwen2.5-VL-7B-Instruct"
  "max_new_tokens": 512
  "temperature": 0
  "device": "cuda"
  "device_map": { "": "cuda" }
  "dtype": "bfloat16"

extra_args:
  model_kwargs:
    max_memory:
      0: "16GiB"
      cpu: "20GiB"
